# Generated by Django 3.2.3 on 2021-06-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_manageunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
