# Generated by Django 3.2.3 on 2021-06-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210628_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
