# Generated by Django 3.2.3 on 2021-07-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_manageunit_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manageunit'),
        ),
    ]
